// GENERATED FILE — do not edit by hand.
// Run `node scripts/generate-industry-codes.mjs` to regenerate.
// Source: https://raw.githubusercontent.com/HarvestAPI/linkedin-industry-codes-v2/main/linkedin_industry_code_v2_all_eng_with_header.csv
//
// LinkedIn industry ids accepted by HarvestAPI's `industryIds` filter, with
// the coarse category each belongs to so the picker can group 434
// options into something navigable.

export type IndustryCode = { id: number; label: string; group: string }

const RAW: Array<[number, string, string]> = [
  [2190, "Accommodation Services", "Accommodation Services"],
  [34, "Food and Beverage Services", "Accommodation Services"],
  [2217, "Bars, Taverns, and Nightclubs", "Accommodation Services"],
  [2212, "Caterers", "Accommodation Services"],
  [2214, "Mobile Food Services", "Accommodation Services"],
  [32, "Restaurants", "Accommodation Services"],
  [31, "Hospitality", "Accommodation Services"],
  [2197, "Bed-and-Breakfasts, Hostels, Homestays", "Accommodation Services"],
  [2194, "Hotels and Motels", "Accommodation Services"],
  [1912, "Administrative and Support Services", "Administrative and Support Services"],
  [1938, "Collection Agencies", "Administrative and Support Services"],
  [110, "Events Services", "Administrative and Support Services"],
  [122, "Facilities Services", "Administrative and Support Services"],
  [1965, "Janitorial Services", "Administrative and Support Services"],
  [2934, "Landscaping Services", "Administrative and Support Services"],
  [101, "Fundraising", "Administrative and Support Services"],
  [1916, "Office Administration", "Administrative and Support Services"],
  [121, "Security and Investigations", "Administrative and Support Services"],
  [1956, "Security Guards and Patrol Services", "Administrative and Support Services"],
  [1958, "Security Systems Services", "Administrative and Support Services"],
  [104, "Staffing and Recruiting", "Administrative and Support Services"],
  [1923, "Executive Search Services", "Administrative and Support Services"],
  [1925, "Temporary Help Services", "Administrative and Support Services"],
  [1931, "Telephone Call Centers", "Administrative and Support Services"],
  [108, "Translation and Localization", "Administrative and Support Services"],
  [30, "Travel Arrangements", "Administrative and Support Services"],
  [103, "Writing and Editing", "Administrative and Support Services"],
  [48, "Construction", "Construction"],
  [406, "Building Construction", "Construction"],
  [413, "Nonresidential Building Construction", "Construction"],
  [408, "Residential Building Construction", "Construction"],
  [51, "Civil Engineering", "Construction"],
  [431, "Highway, Street, and Bridge Construction", "Construction"],
  [428, "Subdivision of Land", "Construction"],
  [419, "Utility System Construction", "Construction"],
  [435, "Specialty Trade Contractors", "Construction"],
  [453, "Building Equipment Contractors", "Construction"],
  [460, "Building Finishing Contractors", "Construction"],
  [436, "Building Structure and Exterior Contractors", "Construction"],
  [91, "Consumer Services", "Consumer Services"],
  [90, "Civic and Social Organizations", "Consumer Services"],
  [1909, "Industry Associations", "Consumer Services"],
  [107, "Political Organizations", "Consumer Services"],
  [1911, "Professional Organizations", "Consumer Services"],
  [2318, "Household Services", "Consumer Services"],
  [100, "Non-profit Organizations", "Consumer Services"],
  [2258, "Personal and Laundry Services", "Consumer Services"],
  [2272, "Laundry and Drycleaning Services", "Consumer Services"],
  [2259, "Personal Care Services", "Consumer Services"],
  [2282, "Pet Services", "Consumer Services"],
  [131, "Philanthropic Fundraising Services", "Consumer Services"],
  [89, "Religious Institutions", "Consumer Services"],
  [2225, "Repair and Maintenance", "Consumer Services"],
  [2247, "Commercial and Industrial Machinery Maintenance", "Consumer Services"],
  [2240, "Electronic and Precision Equipment Maintenance", "Consumer Services"],
  [2255, "Footwear and Leather Goods Repair", "Consumer Services"],
  [2253, "Reupholstery and Furniture Repair", "Consumer Services"],
  [2226, "Vehicle Repair and Maintenance", "Consumer Services"],
  [1999, "Education", "Education"],
  [132, "E-Learning Providers", "Education"],
  [68, "Higher Education", "Education"],
  [67, "Primary and Secondary Education", "Education"],
  [105, "Professional Training and Coaching", "Education"],
  [2018, "Technical and Vocational Training", "Education"],
  [2019, "Cosmetology and Barber Schools", "Education"],
  [2025, "Fine Arts Schools", "Education"],
  [2020, "Flight Training", "Education"],
  [2029, "Language Schools", "Education"],
  [2012, "Secretarial Schools", "Education"],
  [2027, "Sports and Recreation Instruction", "Education"],
  [28, "Entertainment Providers", "Entertainment Providers"],
  [38, "Artists and Writers", "Entertainment Providers"],
  [37, "Museums, Historical Sites, and Zoos", "Entertainment Providers"],
  [2161, "Historical Sites", "Entertainment Providers"],
  [2159, "Museums", "Entertainment Providers"],
  [2163, "Zoos and Botanical Gardens", "Entertainment Providers"],
  [115, "Musicians", "Entertainment Providers"],
  [2130, "Performing Arts and Spectator Sports", "Entertainment Providers"],
  [2139, "Circuses and Magic Shows", "Entertainment Providers"],
  [2135, "Dance Companies", "Entertainment Providers"],
  [39, "Performing Arts", "Entertainment Providers"],
  [33, "Spectator Sports", "Entertainment Providers"],
  [2143, "Racetracks", "Entertainment Providers"],
  [2142, "Sports Teams and Clubs", "Entertainment Providers"],
  [2133, "Theater Companies", "Entertainment Providers"],
  [40, "Recreational Facilities", "Entertainment Providers"],
  [2167, "Amusement Parks and Arcades", "Entertainment Providers"],
  [29, "Gambling Facilities and Casinos", "Entertainment Providers"],
  [2179, "Golf Courses and Country Clubs", "Entertainment Providers"],
  [2181, "Skiing Facilities", "Entertainment Providers"],
  [124, "Wellness and Fitness Services", "Entertainment Providers"],
  [201, "Farming, Ranching, Forestry", "Farming, Ranching, Forestry"],
  [63, "Farming", "Farming, Ranching, Forestry"],
  [150, "Horticulture", "Farming, Ranching, Forestry"],
  [298, "Forestry and Logging", "Farming, Ranching, Forestry"],
  [256, "Ranching and Fisheries", "Farming, Ranching, Forestry"],
  [66, "Fisheries", "Farming, Ranching, Forestry"],
  [64, "Ranching", "Farming, Ranching, Forestry"],
  [43, "Financial Services", "Financial Services"],
  [129, "Capital Markets", "Financial Services"],
  [1720, "Investment Advice", "Financial Services"],
  [45, "Investment Banking", "Financial Services"],
  [46, "Investment Management", "Financial Services"],
  [1713, "Securities and Commodity Exchanges", "Financial Services"],
  [106, "Venture Capital and Private Equity Principals", "Financial Services"],
  [1673, "Credit Intermediation", "Financial Services"],
  [41, "Banking", "Financial Services"],
  [141, "International Trade and Development", "Financial Services"],
  [1696, "Loan Brokers", "Financial Services"],
  [1678, "Savings Institutions", "Financial Services"],
  [1742, "Funds and Trusts", "Financial Services"],
  [1743, "Insurance and Employee Benefit Funds", "Financial Services"],
  [1745, "Pension Funds", "Financial Services"],
  [1750, "Trusts and Estates", "Financial Services"],
  [42, "Insurance", "Financial Services"],
  [1738, "Claims Adjusting, Actuarial Services", "Financial Services"],
  [1737, "Insurance Agencies and Brokerages", "Financial Services"],
  [1725, "Insurance Carriers", "Financial Services"],
  [75, "Government Administration", "Government Administration"],
  [73, "Administration of Justice", "Government Administration"],
  [3068, "Correctional Institutions", "Government Administration"],
  [3065, "Courts of Law", "Government Administration"],
  [3070, "Fire Protection", "Government Administration"],
  [77, "Law Enforcement", "Government Administration"],
  [78, "Public Safety", "Government Administration"],
  [2375, "Economic Programs", "Government Administration"],
  [3085, "Transportation Programs", "Government Administration"],
  [3086, "Utilities Administration", "Government Administration"],
  [388, "Environmental Quality Programs", "Government Administration"],
  [2366, "Air, Water, and Waste Program Management", "Government Administration"],
  [2368, "Conservation Programs", "Government Administration"],
  [2353, "Health and Human Services", "Government Administration"],
  [69, "Education Administration Programs", "Government Administration"],
  [2360, "Public Assistance Programs", "Government Administration"],
  [2358, "Public Health", "Government Administration"],
  [2369, "Housing and Community Development", "Government Administration"],
  [2374, "Community Development and Urban Planning", "Government Administration"],
  [3081, "Housing Programs", "Government Administration"],
  [2391, "Military and International Affairs", "Government Administration"],
  [71, "Armed Forces", "Government Administration"],
  [74, "International Affairs", "Government Administration"],
  [79, "Public Policy Offices", "Government Administration"],
  [76, "Executive Offices", "Government Administration"],
  [72, "Legislative Offices", "Government Administration"],
  [3089, "Space Research and Technology", "Government Administration"],
  [1905, "Holding Companies", "Holding Companies"],
  [14, "Hospitals and Health Care", "Hospitals and Health Care"],
  [2115, "Community Services", "Hospitals and Health Care"],
  [2112, "Services for the Elderly and Disabled", "Hospitals and Health Care"],
  [2081, "Hospitals", "Hospitals and Health Care"],
  [88, "Individual and Family Services", "Hospitals and Health Care"],
  [2128, "Child Day Care Services", "Hospitals and Health Care"],
  [2122, "Emergency and Relief Services", "Hospitals and Health Care"],
  [2125, "Vocational Rehabilitation Services", "Hospitals and Health Care"],
  [13, "Medical Practices", "Hospitals and Health Care"],
  [125, "Alternative Medicine", "Hospitals and Health Care"],
  [2077, "Ambulance Services", "Hospitals and Health Care"],
  [2048, "Chiropractors", "Hospitals and Health Care"],
  [2045, "Dentists", "Hospitals and Health Care"],
  [2060, "Family Planning Centers", "Hospitals and Health Care"],
  [2074, "Home Health Care Services", "Hospitals and Health Care"],
  [2069, "Medical and Diagnostic Laboratories", "Hospitals and Health Care"],
  [139, "Mental Health Care", "Hospitals and Health Care"],
  [2050, "Optometrists", "Hospitals and Health Care"],
  [2063, "Outpatient Care Centers", "Hospitals and Health Care"],
  [2054, "Physical, Occupational and Speech Therapists", "Hospitals and Health Care"],
  [2040, "Physicians", "Hospitals and Health Care"],
  [2091, "Nursing Homes and Residential Care Facilities", "Hospitals and Health Care"],
  [25, "Manufacturing", "Manufacturing"],
  [598, "Apparel Manufacturing", "Manufacturing"],
  [615, "Fashion Accessories Manufacturing", "Manufacturing"],
  [112, "Appliances, Electrical, and Electronics Manufacturing", "Manufacturing"],
  [998, "Electric Lighting Equipment Manufacturing", "Manufacturing"],
  [2468, "Electrical Equipment Manufacturing", "Manufacturing"],
  [3255, "Fuel Cell Manufacturing", "Manufacturing"],
  [1005, "Household Appliance Manufacturing", "Manufacturing"],
  [54, "Chemical Manufacturing", "Manufacturing"],
  [709, "Agricultural Chemical Manufacturing", "Manufacturing"],
  [703, "Artificial Rubber and Synthetic Fiber Manufacturing", "Manufacturing"],
  [690, "Chemical Raw Materials Manufacturing", "Manufacturing"],
  [722, "Paint, Coating, and Adhesive Manufacturing", "Manufacturing"],
  [18, "Personal Care Product Manufacturing", "Manufacturing"],
  [15, "Pharmaceutical Manufacturing", "Manufacturing"],
  [727, "Soap and Cleaning Product Manufacturing", "Manufacturing"],
  [3251, "Climate Technology Product Manufacturing", "Manufacturing"],
  [24, "Computers and Electronics Manufacturing", "Manufacturing"],
  [973, "Audio and Video Equipment Manufacturing", "Manufacturing"],
  [964, "Communications Equipment Manufacturing", "Manufacturing"],
  [3, "Computer Hardware Manufacturing", "Manufacturing"],
  [3245, "Accessible Hardware Manufacturing", "Manufacturing"],
  [994, "Magnetic and Optical Media Manufacturing", "Manufacturing"],
  [983, "Measuring and Control Instrument Manufacturing", "Manufacturing"],
  [3254, "Smart Meter Manufacturing", "Manufacturing"],
  [7, "Semiconductor Manufacturing", "Manufacturing"],
  [144, "Renewable Energy Semiconductor Manufacturing", "Manufacturing"],
  [840, "Fabricated Metal Products", "Manufacturing"],
  [852, "Architectural and Structural Metal Manufacturing", "Manufacturing"],
  [861, "Boilers, Tanks, and Shipping Container Manufacturing", "Manufacturing"],
  [871, "Construction Hardware Manufacturing", "Manufacturing"],
  [849, "Cutlery and Handtool Manufacturing", "Manufacturing"],
  [883, "Metal Treatments", "Manufacturing"],
  [887, "Metal Valve, Ball, and Roller Manufacturing", "Manufacturing"],
  [873, "Spring and Wire Product Manufacturing", "Manufacturing"],
  [876, "Turned Products and Fastener Manufacturing", "Manufacturing"],
  [23, "Food and Beverage Manufacturing", "Manufacturing"],
  [562, "Breweries", "Manufacturing"],
  [564, "Distilleries", "Manufacturing"],
  [2500, "Wineries", "Manufacturing"],
  [481, "Animal Feed Manufacturing", "Manufacturing"],
  [529, "Baked Goods Manufacturing", "Manufacturing"],
  [142, "Beverage Manufacturing", "Manufacturing"],
  [65, "Dairy Product Manufacturing", "Manufacturing"],
  [504, "Fruit and Vegetable Preserves Manufacturing", "Manufacturing"],
  [521, "Meat Products Manufacturing", "Manufacturing"],
  [528, "Seafood Product Manufacturing", "Manufacturing"],
  [495, "Sugar and Confectionery Product Manufacturing", "Manufacturing"],
  [26, "Furniture and Home Furnishings Manufacturing", "Manufacturing"],
  [1080, "Household and Institutional Furniture Manufacturing", "Manufacturing"],
  [1095, "Mattress and Blinds Manufacturing", "Manufacturing"],
  [1090, "Office Furniture and Fixtures Manufacturing", "Manufacturing"],
  [145, "Glass, Ceramics and Concrete Manufacturing", "Manufacturing"],
  [799, "Abrasives and Nonmetallic Minerals Manufacturing", "Manufacturing"],
  [773, "Clay and Refractory Products Manufacturing", "Manufacturing"],
  [779, "Glass Product Manufacturing", "Manufacturing"],
  [794, "Lime and Gypsum Products Manufacturing", "Manufacturing"],
  [616, "Leather Product Manufacturing", "Manufacturing"],
  [622, "Footwear Manufacturing", "Manufacturing"],
  [625, "Women's Handbag Manufacturing", "Manufacturing"],
  [55, "Machinery Manufacturing", "Manufacturing"],
  [901, "Agriculture, Construction, Mining Machinery Manufacturing", "Manufacturing"],
  [147, "Automation Machinery Manufacturing", "Manufacturing"],
  [3247, "Robot Manufacturing", "Manufacturing"],
  [918, "Commercial and Service Industry Machinery Manufacturing", "Manufacturing"],
  [935, "Engines and Power Transmission Equipment Manufacturing", "Manufacturing"],
  [3241, "Renewable Energy Equipment Manufacturing", "Manufacturing"],
  [923, "HVAC and Refrigeration Equipment Manufacturing", "Manufacturing"],
  [135, "Industrial Machinery Manufacturing", "Manufacturing"],
  [928, "Metalworking Machinery Manufacturing", "Manufacturing"],
  [17, "Medical Equipment Manufacturing", "Manufacturing"],
  [679, "Oil and Coal Product Manufacturing", "Manufacturing"],
  [61, "Paper and Forest Product Manufacturing", "Manufacturing"],
  [743, "Plastics and Rubber Product Manufacturing", "Manufacturing"],
  [146, "Packaging and Containers Manufacturing", "Manufacturing"],
  [117, "Plastics Manufacturing", "Manufacturing"],
  [763, "Rubber Products Manufacturing", "Manufacturing"],
  [807, "Primary Metal Manufacturing", "Manufacturing"],
  [83, "Printing Services", "Manufacturing"],
  [20, "Sporting Goods Manufacturing", "Manufacturing"],
  [60, "Textile Manufacturing", "Manufacturing"],
  [21, "Tobacco Manufacturing", "Manufacturing"],
  [1029, "Transportation Equipment Manufacturing", "Manufacturing"],
  [52, "Aviation and Aerospace Component Manufacturing", "Manufacturing"],
  [1, "Defense and Space Manufacturing", "Manufacturing"],
  [53, "Motor Vehicle Manufacturing", "Manufacturing"],
  [3253, "Alternative Fuel Vehicle Manufacturing", "Manufacturing"],
  [1042, "Motor Vehicle Parts Manufacturing", "Manufacturing"],
  [62, "Railroad Equipment Manufacturing", "Manufacturing"],
  [58, "Shipbuilding", "Manufacturing"],
  [784, "Wood Product Manufacturing", "Manufacturing"],
  [332, "Oil, Gas, and Mining", "Oil, Gas, and Mining"],
  [56, "Mining", "Oil, Gas, and Mining"],
  [341, "Coal Mining", "Oil, Gas, and Mining"],
  [345, "Metal Ore Mining", "Oil, Gas, and Mining"],
  [356, "Nonmetallic Mineral Mining", "Oil, Gas, and Mining"],
  [57, "Oil and Gas", "Oil, Gas, and Mining"],
  [3096, "Natural Gas Extraction", "Oil, Gas, and Mining"],
  [3095, "Oil Extraction", "Oil, Gas, and Mining"],
  [1810, "Professional Services", "Professional Services"],
  [47, "Accounting", "Professional Services"],
  [80, "Advertising Services", "Professional Services"],
  [148, "Government Relations Services", "Professional Services"],
  [98, "Public Relations and Communications Services", "Professional Services"],
  [97, "Market Research", "Professional Services"],
  [50, "Architecture and Planning", "Professional Services"],
  [3246, "Accessible Architecture and Design", "Professional Services"],
  [11, "Business Consulting and Services", "Professional Services"],
  [86, "Environmental Services", "Professional Services"],
  [137, "Human Resources Services", "Professional Services"],
  [1862, "Marketing Services", "Professional Services"],
  [2401, "Operations Consulting", "Professional Services"],
  [123, "Outsourcing and Offshoring Consulting", "Professional Services"],
  [102, "Strategic Management Services", "Professional Services"],
  [99, "Design Services", "Professional Services"],
  [140, "Graphic Design", "Professional Services"],
  [3256, "Regenerative Design", "Professional Services"],
  [3126, "Interior Design", "Professional Services"],
  [3242, "Engineering Services", "Professional Services"],
  [3248, "Robotics Engineering", "Professional Services"],
  [3249, "Surveying and Mapping Services", "Professional Services"],
  [96, "IT Services and IT Consulting", "Professional Services"],
  [118, "Computer and Network Security", "Professional Services"],
  [3244, "Digital Accessibility Services", "Professional Services"],
  [3102, "IT System Custom Software Development", "Professional Services"],
  [3106, "IT System Data Services", "Professional Services"],
  [1855, "IT System Design Services", "Professional Services"],
  [3104, "IT System Installation and Disposal", "Professional Services"],
  [3103, "IT System Operations and Maintenance", "Professional Services"],
  [3107, "IT System Testing and Evaluation", "Professional Services"],
  [3105, "IT System Training and Support", "Professional Services"],
  [10, "Legal Services", "Professional Services"],
  [120, "Alternative Dispute Resolution", "Professional Services"],
  [9, "Law Practice", "Professional Services"],
  [136, "Photography", "Professional Services"],
  [70, "Research Services", "Professional Services"],
  [12, "Biotechnology Research", "Professional Services"],
  [114, "Nanotechnology Research", "Professional Services"],
  [130, "Think Tanks", "Professional Services"],
  [3243, "Services for Renewable Energy", "Professional Services"],
  [16, "Veterinary Services", "Professional Services"],
  [1757, "Real Estate and Equipment Rental Services", "Real Estate and Equipment Rental Services"],
  [1779, "Equipment Rental Services", "Real Estate and Equipment Rental Services"],
  [1798, "Commercial and Industrial Equipment Rental", "Real Estate and Equipment Rental Services"],
  [1786, "Consumer Goods Rental", "Real Estate and Equipment Rental Services"],
  [44, "Real Estate", "Real Estate and Equipment Rental Services"],
  [128, "Leasing Non-residential Real Estate", "Real Estate and Equipment Rental Services"],
  [1759, "Leasing Residential Real Estate", "Real Estate and Equipment Rental Services"],
  [1770, "Real Estate Agents and Brokers", "Real Estate and Equipment Rental Services"],
  [27, "Retail", "Retail"],
  [1339, "Food and Beverage Retail", "Retail"],
  [22, "Retail Groceries", "Retail"],
  [1445, "Online and Mail Order Retail", "Retail"],
  [19, "Retail Apparel and Fashion", "Retail"],
  [1319, "Retail Appliances, Electrical, and Electronic Equipment", "Retail"],
  [3186, "Retail Art Dealers", "Retail"],
  [111, "Retail Art Supplies", "Retail"],
  [1409, "Retail Books and Printed News", "Retail"],
  [1324, "Retail Building Materials and Garden Equipment", "Retail"],
  [1423, "Retail Florists", "Retail"],
  [1309, "Retail Furniture and Home Furnishings", "Retail"],
  [1370, "Retail Gasoline", "Retail"],
  [1359, "Retail Health and Personal Care Products", "Retail"],
  [3250, "Retail Pharmacies", "Retail"],
  [143, "Retail Luxury Goods and Jewelry", "Retail"],
  [1292, "Retail Motor Vehicles", "Retail"],
  [1407, "Retail Musical Instruments", "Retail"],
  [138, "Retail Office Equipment", "Retail"],
  [1424, "Retail Office Supplies and Gifts", "Retail"],
  [1431, "Retail Recyclable Materials & Used Merchandise", "Retail"],
  [1594, "Technology, Information and Media", "Technology, Information and Media"],
  [3133, "Media & Telecommunications", "Technology, Information and Media"],
  [82, "Book and Periodical Publishing", "Technology, Information and Media"],
  [1602, "Book Publishing", "Technology, Information and Media"],
  [81, "Newspaper Publishing", "Technology, Information and Media"],
  [1600, "Periodical Publishing", "Technology, Information and Media"],
  [36, "Broadcast Media Production and Distribution", "Technology, Information and Media"],
  [1641, "Cable and Satellite Programming", "Technology, Information and Media"],
  [1633, "Radio and Television Broadcasting", "Technology, Information and Media"],
  [35, "Movies, Videos and Sound", "Technology, Information and Media"],
  [127, "Animation and Post-production", "Technology, Information and Media"],
  [126, "Media Production", "Technology, Information and Media"],
  [1611, "Movies and Sound Recording", "Technology, Information and Media"],
  [1623, "Sound Recording", "Technology, Information and Media"],
  [1625, "Sheet Music Publishing", "Technology, Information and Media"],
  [8, "Telecommunications", "Technology, Information and Media"],
  [1649, "Satellite Telecommunications", "Technology, Information and Media"],
  [1644, "Telecommunications Carriers", "Technology, Information and Media"],
  [119, "Wireless Services", "Technology, Information and Media"],
  [6, "Technology, Information and Internet", "Technology, Information and Media"],
  [2458, "Data Infrastructure and Analytics", "Technology, Information and Media"],
  [3134, "Blockchain Services", "Technology, Information and Media"],
  [3128, "Business Intelligence Platforms", "Technology, Information and Media"],
  [3252, "Climate Data and Analytics", "Technology, Information and Media"],
  [84, "Information Services", "Technology, Information and Media"],
  [3132, "Internet Publishing", "Technology, Information and Media"],
  [3129, "Business Content", "Technology, Information and Media"],
  [113, "Online Audio and Video Media", "Technology, Information and Media"],
  [3124, "Internet News", "Technology, Information and Media"],
  [85, "Libraries", "Technology, Information and Media"],
  [3125, "Blogs", "Technology, Information and Media"],
  [1285, "Internet Marketplace Platforms", "Technology, Information and Media"],
  [3127, "Social Networking Platforms", "Technology, Information and Media"],
  [4, "Software Development", "Technology, Information and Media"],
  [109, "Computer Games", "Technology, Information and Media"],
  [3131, "Mobile Gaming Apps", "Technology, Information and Media"],
  [5, "Computer Networking Products", "Technology, Information and Media"],
  [3130, "Data Security Software Products", "Technology, Information and Media"],
  [3101, "Desktop Computing Software Products", "Technology, Information and Media"],
  [3099, "Embedded Software Products", "Technology, Information and Media"],
  [3100, "Mobile Computing Software Products", "Technology, Information and Media"],
  [116, "Transportation, Logistics, Supply Chain and Storage", "Transportation, Logistics, Supply Chain and Storage"],
  [94, "Airlines and Aviation", "Transportation, Logistics, Supply Chain and Storage"],
  [87, "Freight and Package Transportation", "Transportation, Logistics, Supply Chain and Storage"],
  [1495, "Ground Passenger Transportation", "Transportation, Logistics, Supply Chain and Storage"],
  [1504, "Interurban and Rural Bus Services", "Transportation, Logistics, Supply Chain and Storage"],
  [1512, "School and Employee Bus Services", "Transportation, Logistics, Supply Chain and Storage"],
  [1517, "Shuttles and Special Needs Transportation Services", "Transportation, Logistics, Supply Chain and Storage"],
  [1532, "Sightseeing Transportation", "Transportation, Logistics, Supply Chain and Storage"],
  [1505, "Taxi and Limousine Services", "Transportation, Logistics, Supply Chain and Storage"],
  [1497, "Urban Transit Services", "Transportation, Logistics, Supply Chain and Storage"],
  [95, "Maritime Transportation", "Transportation, Logistics, Supply Chain and Storage"],
  [1520, "Pipeline Transportation", "Transportation, Logistics, Supply Chain and Storage"],
  [1573, "Postal Services", "Transportation, Logistics, Supply Chain and Storage"],
  [1481, "Rail Transportation", "Transportation, Logistics, Supply Chain and Storage"],
  [92, "Truck Transportation", "Transportation, Logistics, Supply Chain and Storage"],
  [93, "Warehousing and Storage", "Transportation, Logistics, Supply Chain and Storage"],
  [59, "Utilities", "Utilities"],
  [383, "Electric Power Generation", "Utilities"],
  [385, "Fossil Fuel Electric Power Generation", "Utilities"],
  [386, "Nuclear Electric Power Generation", "Utilities"],
  [3240, "Renewable Energy Power Generation", "Utilities"],
  [390, "Biomass Electric Power Generation", "Utilities"],
  [389, "Geothermal Electric Power Generation", "Utilities"],
  [384, "Hydroelectric Power Generation", "Utilities"],
  [387, "Solar Electric Power Generation", "Utilities"],
  [2489, "Wind Electric Power Generation", "Utilities"],
  [382, "Electric Power Transmission, Control, and Distribution", "Utilities"],
  [397, "Natural Gas Distribution", "Utilities"],
  [398, "Water, Waste, Steam, and Air Conditioning Services", "Utilities"],
  [404, "Steam and Air-Conditioning Supply", "Utilities"],
  [1981, "Waste Collection", "Utilities"],
  [1986, "Waste Treatment and Disposal", "Utilities"],
  [400, "Water Supply and Irrigation Systems", "Utilities"],
  [133, "Wholesale", "Wholesale"],
  [1267, "Wholesale Alcoholic Beverages", "Wholesale"],
  [1222, "Wholesale Apparel and Sewing Supplies", "Wholesale"],
  [1171, "Wholesale Appliances, Electrical, and Electronics", "Wholesale"],
  [49, "Wholesale Building Materials", "Wholesale"],
  [1257, "Wholesale Chemical and Allied Products", "Wholesale"],
  [1157, "Wholesale Computer Equipment", "Wholesale"],
  [1221, "Wholesale Drugs and Sundries", "Wholesale"],
  [1231, "Wholesale Food and Beverage", "Wholesale"],
  [1230, "Wholesale Footwear", "Wholesale"],
  [1137, "Wholesale Furniture and Home Furnishings", "Wholesale"],
  [1178, "Wholesale Hardware, Plumbing, Heating Equipment", "Wholesale"],
  [134, "Wholesale Import and Export", "Wholesale"],
  [1208, "Wholesale Luxury Goods and Jewelry", "Wholesale"],
  [1187, "Wholesale Machinery", "Wholesale"],
  [1166, "Wholesale Metals and Minerals", "Wholesale"],
  [1128, "Wholesale Motor Vehicles and Parts", "Wholesale"],
  [1212, "Wholesale Paper Products", "Wholesale"],
  [1262, "Wholesale Petroleum and Petroleum Products", "Wholesale"],
  [1153, "Wholesale Photography Equipment and Supplies", "Wholesale"],
  [1250, "Wholesale Raw Farm Products", "Wholesale"],
  [1206, "Wholesale Recyclable Materials", "Wholesale"],
]

export const INDUSTRY_CODES: IndustryCode[] = RAW.map(([id, label, group]) => ({ id, label, group }))

export const INDUSTRY_BY_ID = new Map<number, IndustryCode>(
  INDUSTRY_CODES.map(i => [i.id, i])
)

/** Coarse categories, in the order they first appear in LinkedIn's own list. */
export const INDUSTRY_GROUPS: string[] = [...new Set(INDUSTRY_CODES.map(i => i.group))]

/** Case-insensitive substring match over labels, for the picker's search box. */
export function searchIndustries(query: string, limit = 50): IndustryCode[] {
  const q = query.trim().toLowerCase()
  if (!q) return []
  const out: IndustryCode[] = []
  for (const item of INDUSTRY_CODES) {
    if (item.label.toLowerCase().includes(q)) {
      out.push(item)
      if (out.length >= limit) break
    }
  }
  return out
}
